version: "3.9"

services:
    db:
        image: postgres:13
        restart: always
        container_name: test-db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tests
    # redis:
    #     image: redis:6.2.4
    #     restart: always
    #     ports:
    #         - "6380:6379"
